### PR TITLE
theme: Add support switching to other languages

### PR DESCRIPTION
**Pull request by Holzhaus**
This adds a little language widget to the sidebar:

2020-02-21-151519_534x628_scrot

### CODE REVIEW

**Comment by Holzhaus** [comment]
jenkins: test this please

**Comment by rryan** [comment]
Should language names be translated or are we ok with showing the English name of the language?

**Comment by rryan** [comment]
jenkins: test this please

**Comment by Holzhaus** [comment]
> Should language names be translated

Yes. Can I just replace `{{ langname }}` with `{{ _(langname) }}` in the sidebar widget template? Or will that not work because there is some static analysis going on that is unable to resolve the contents of the `langname` variable?

**Comment by rryan** [comment]
> Yes. Can I just replace `{{ langname }}` with `{{ _(langname) }}` in the sidebar widget template? Or will that not work because there is some static analysis going on that is unable to resolve the contents of the `langname` variable?

I'm not sure? Maybe try that and run `make gettext` to see if any `.pot`'s in `source/locale/pot` include the language names?

**Comment by Holzhaus** [comment]
```
writing message catalogs... [  4%] sphinx
Exception occurred:
  File "/usr/lib/python3.8/site-packages/sphinx/builders/gettext.py", line 118, in escape
    s = s.replace('\\', r'\\')
AttributeError: 'NoneType' object has no attribute 'replace'
The full traceback has been saved in /tmp/sphinx-err-8_rj8lny.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [Makefile:151: gettext] Fehler 2
```

**Comment by rryan** [comment]
If we could translate strings in conf.py then that could be an option, but it doesn't seem to work. Asked on sphinx-users: https://groups.google.com/forum/#!topic/sphinx-users/qdgAAJ6lbG4

**Comment by Holzhaus** [comment]
We could also work around it by using the localized name directly, i. e. 'en' shows up as 'English', 'de' shows up as 'Deutsch', 'fi' as 'Suomi', etc.

**Comment by Holzhaus** [comment]
jenkins test this please

**Comment by rryan** [comment]
This looks good to go and very useful, thanks!  Since CI is being flaky, let's just merge.

**Pull request merged**
