### PR TITLE
Add [Library],show_track_menu

### PR DESCRIPTION
**Pull request by ronso0**
docu for https://github.com/mixxxdj/mixxx/pull/4465

### CODE REVIEW

**Comment by Swiftb0y** [comment]
In the associated PR [you said](https://github.com/mixxxdj/mixxx/pull/4465#issuecomment-1014586700) there were some limitations with this CO. and we agreed to mention them in the manual. An explanation of these caveats got lost. Would you mind adding them?

**Comment by ronso0** [comment]
Thanks for the reminder!
updated and force-pushed

https://deploy-preview-475--mixxx-manual.netlify.app/chapters/appendix/mixxx_controls.html#control-[Library]-show_track_menu

**Review by Swiftb0y — APPROVED** [review]
Thanks

**Comment by ronso0** [comment]
merge?

**Review by Swiftb0y — APPROVED** [review]

**Pull request merged**
