### PR TITLE
Fix htaccess redirects and add test script

### PR DESCRIPTION
**Pull request by Holzhaus**
This is a new iteration of #102. This time I tested it locally on an Apache 2.4 instance. It works fine for me. I also added some tests that use curl to determine if all redirects work.

### CODE REVIEW

**Comment by Holzhaus** [comment]
Here's how the tests look when this htacess is used:

```
Running tests using base URL: http://localhost/2.3
Redirect from "" to "en/" with args ""... OK
Redirect from "chapters" to "en/chapters" with args ""... OK
Redirect from "chapters/user_interface.html" to "en/chapters/user_interface.html" with args ""... OK
Redirect from "Mixxx-Manual.pdf" to "en/Mixxx-Manual.pdf" with args ""... OK
Redirect from "" to "de/" with args "-H Accept-Language: de"... OK
Redirect from "chapters" to "de/chapters" with args "-H Accept-Language: de"... OK
Redirect from "chapters/user_interface.html" to "de/chapters/user_interface.html" with args "-H Accept-Language: de"... OK
Redirect from "Mixxx-Manual.pdf" to "de/Mixxx-Manual.pdf" with args "-H Accept-Language: de"... OK
Redirect from "" to "de-DE/" with args "-H Accept-Language: de-DE, de"... OK
Redirect from "chapters" to "de-DE/chapters" with args "-H Accept-Language: de-DE, de"... OK
Redirect from "chapters/user_interface.html" to "de-DE/chapters/user_interface.html" with args "-H Accept-Language: de-DE, de"... OK
Redirect from "Mixxx-Manual.pdf" to "de-DE/Mixxx-Manual.pdf" with args "-H Accept-Language: de-DE, de"... OK
Redirect from "" to "de/" with args "-H Accept-Language: xxx, de;q=0.9, en;q=0.8"... OK
Redirect from "chapters" to "de/chapters" with args "-H Accept-Language: xxx, de;q=0.9, en;q=0.8"... OK
Redirect from "chapters/user_interface.html" to "de/chapters/user_interface.html" with args "-H Accept-Language: xxx, de;q=0.9, en;q=0.8"... OK
Redirect from "Mixxx-Manual.pdf" to "de/Mixxx-Manual.pdf" with args "-H Accept-Language: xxx, de;q=0.9, en;q=0.8"... OK
Do not redirect from "es/" with args ""... OK
Do not redirect from "es/" with args "-H Accept-Language: de"... OK
Do not redirect from "es/chapters" with args ""... OK
Do not redirect from "es/chapters" with args "-H Accept-Language: de"... OK
Do not redirect from "es/chapters/user_interface.html" with args ""... OK
Do not redirect from "es/chapters/user_interface.html" with args "-H Accept-Language: de"... OK
Do not redirect from "es/Mixxx-Manual.pdf" with args ""... OK
Do not redirect from "es/Mixxx-Manual.pdf" with args "-H Accept-Language: de"... OK
```

**Comment by Be-ing** [comment]
Not working. https://staging.mixxx.org/manual/latest/en/ is redirecting to https://staging.mixxx.org/en/en and http://staging.mixxx.org/manual/latest/ does not redirect for the language

**Comment by Holzhaus** [comment]
> Not working. https://staging.mixxx.org/manual/latest/en/ is redirecting to https://staging.mixxx.org/en/en and http://staging.mixxx.org/manual/latest/ does not redirect for the language

That sounds like htaccess file is not deployed into `manual/latest` directory but to the `manual/latest/en` directory instead?

**Comment by Be-ing** [comment]
ping @rryan

**Comment by Holzhaus** [comment]
Oh I was wrong. It *is* deployed into the `manual/latest` directory, but I put it into `manual` when testing locally.

**Comment by Holzhaus** [comment]
We can either move the htaccess file or I just update rules.

**Comment by Holzhaus** [comment]
wait a sec, I'm on it

**Comment by Holzhaus** [comment]
Ok this was much harder than I thought. I need to set a RewriteBase which would require creating a modified htaccess file for each path. Instead, I moved all the logic back into the main htaccess file (I hope jenkins doesn't fail because I deleted `per-version-htaccess`).

**Comment by Holzhaus** [comment]
Wohoo, I think it works! Ping @Be-ing

**Comment by Be-ing** [comment]
http://staging.mixxx.org/manual/latest/en/chapters/vinyl_control.html works but http://staging.mixxx.org/manual/ and http://staging.mixxx.org/manual/latest still redirect to http://staging.mixxx.org/en/en

**Comment by Holzhaus** [comment]
> but http://staging.mixxx.org/manual/ and http://staging.mixxx.org/manual/latest still redirect to http://staging.mixxx.org/en/en

Maybe a caching issue? For me it redirects to http://staging.mixxx.org/manual/latest/de-DE/

**Comment by Be-ing** [comment]
Yup, I cleared Firefox's cache and it worked. Thanks!

**Comment by Holzhaus** [comment]
@rryan do you want to use the test script from Jenkins?

**Comment by esbrandt** [comment]
@Holzhaus 
Is this fixed for the live version, because it gives 403: Forbidden, see #111

**Pull request merged**
