### PR TITLE
htaccess: Simplify and fix htaccess language rewrite rules

### PR DESCRIPTION
**Pull request by Holzhaus**
This is an attempt to fix the redirect issues with languages that cause broken links on our homepage. I did not test this at all, so please verify that it works.

Zulip Discussion: https://mixxx.zulipchat.com/#narrow/stream/109176-documentation/topic/Improving.20the.20Manual.20website/near/190550138

### CODE REVIEW

**Comment by Be-ing** [comment]
It's already broken, so if this doesn't work, let's just try again.

**Comment by Holzhaus** [comment]
@rryan does Jenkins even apply the new htacess after merge automatically?

**Comment by rryan** [comment]
Let's revert since http://mixxx.org/manual/2.2/ does not redirect anywhere.

**Comment by Be-ing** [comment]
It didn't before this was merged either, so reverting wouldn't help.

**Comment by rryan** [comment]
I think Jenkins PR builds of the manual could deploy to staging.mixxx.org which would enable testing.

**Comment by rryan** [comment]
> It didn't before this was merged either, so reverting wouldn't help.

Yes it did, in English at least.

**Comment by rryan** [comment]
I temporarily reverted this live to demonstrate. See: http://mixxx.org/manual/2.3/

**Comment by rryan** [comment]
For people for whom it did not work, does your browser not send the Accept-Language header?

**Comment by rryan** [comment]
```
$ curl -Il -H 'Accept-Language: en' http://direct.mixxx.org/manual/2.3/index.html
HTTP/1.1 301 Moved Permanently
Server: nginx/1.10.3 (Ubuntu)
Date: Fri, 17 Apr 2020 16:28:14 GMT
Content-Type: text/html; charset=iso-8859-1
Connection: keep-alive
Location: http://direct.mixxx.org/manual/2.3/en/index.html

$ curl -Il -H 'Accept-Language: en-us' http://direct.mixxx.org/manual/2.3/index.html
HTTP/1.1 301 Moved Permanently
Server: nginx/1.10.3 (Ubuntu)
Date: Fri, 17 Apr 2020 16:28:30 GMT
Content-Type: text/html; charset=iso-8859-1
Connection: keep-alive
Location: http://direct.mixxx.org/manual/2.3/en/index.html

```

**Comment by Holzhaus** [comment]
I guess I need to setup a local apache instance to test this properly. I old htacess file is very hard to read and ever harder tonmodify. In theory my changes should have worked, maybe there's a tiny bug somewhere.

**Pull request merged**
