### PR TITLE
chapters/advanced_topics: Improve Mixxx control documentation

### PR DESCRIPTION
**Pull request by Holzhaus**
Improve formatting/wording and add missing `:coref:`s.

### CODE REVIEW

**Comment by ronso0** [comment]
maybe also mass-rename `:feedback: N/A` to `:feedback: (none)` or even remove it entirely?

**Comment by Holzhaus** [comment]
> maybe also mass-rename `:feedback: N/A` to `:feedback: (none)` or even remove it entirely?

I replaced it with "None". I thought about removing it, but then you can't tell if there is no feedback or if it's just not documented yet.

**Comment by ronso0** [comment]
the reason I suggested was that I stumbled over `:feedback: (none)`
please rename `:feedback: (none)` also to `:feedback: None` then this is ready.

**Comment by Holzhaus** [comment]
> the reason I suggested was that I stumbled over `:feedback: (none)`
> please rename `:feedback: (none)` also to `:feedback: None` then this is ready.

Done,

**Comment by ronso0** [comment]
Thanks, LGTM

**Pull request merged**
