### PR TITLE
Fix broken tables of hotcue_x controls

### PR DESCRIPTION
**Pull request by ronso0**
before:
https://manual.mixxx.org/2.4/en/chapters/appendix/mixxx_controls.html#control-[ChannelN]-hotcue_X_enabled

now:
https://deploy-preview-491--mixxx-manual.netlify.app/chapters/appendix/mixxx_controls.html#control-[ChannelN]-hotcue_X_enabled

### CODE REVIEW

**Comment by ronso0** [comment]
This is just a quick fix which expands the first column. Any other idea how to fix this?

**Comment by Holzhaus** [comment]
We could also make it a separate field, like "Writable: No".

**Review by Holzhaus — APPROVED** [review]
LGTM, thank you

**Comment by ronso0** [comment]
> We could also make it a separate field, like "Writable: No".

a "field" like `range` or do you mean a separate column?

**Comment by Holzhaus** [comment]
> > We could also make it a separate field, like "Writable: No".
> 
> a "field" like `range` or do you mean a separate column?

yes, a field like `range`. But I'm not sure if this takes too much space.

**Comment by ronso0** [comment]
worth a try.
where are fields defined? didn't find it with grep range

**Pull request merged**
