### PR TITLE
source/chapters/advanced_topics: Remove [AutoDJ],add_random_track control

### PR DESCRIPTION
**Pull request by Holzhaus**
This does not actually exist in Mixxx 2.3. Work is still pending in mixxxdj/mixxx#3076 and will probably be merged into Mixxx 2.4.

### CODE REVIEW

**Comment by ronso0** [comment]
Thanks!

**Comment by Holzhaus** [comment]
@PawBud Can you add a PR targeted at `main` that reverts commit https://github.com/mixxxdj/manual/pull/255/commits/78d3a4a3c7e22c0748b302017611cd1c6c398b1b ?

**Comment by PawBud** [comment]
> @PawBud Can you add a PR targeted at `main` that reverts commit [78d3a4a](https://github.com/mixxxdj/manual/commit/78d3a4a3c7e22c0748b302017611cd1c6c398b1b)?
Oops, I am so sorry I didn't get the notification for this message. I'll do it right away @Holzhaus

**Comment by Holzhaus** [comment]
@PawBud I already took care of that here: https://github.com/mixxxdj/manual/pull/277

**Comment by PawBud** [comment]
I am sorry for the trouble

**Comment by Holzhaus** [comment]
No problem :smiley:

**Pull request merged**
