### PR TITLE
Fix Sidebar on mobile

### PR DESCRIPTION
**Pull request by Holzhaus**

### CODE REVIEW

**Comment by Holzhaus** [comment]
Dear Jenkins, would you kindly build this please

**Comment by Holzhaus** [comment]
Jenkins build this please

**Comment by Holzhaus** [comment]
Jenkins build this please

**Comment by rryan** [comment]
jenkins: test this please

**Comment by Holzhaus** [comment]
Strange, this works on my desktop when I make the window small, but not on my phone.

**Comment by Holzhaus** [comment]
Maybe there is some caching going on? When I `make html` locally then cd to `build/html` and run `python -m http.server`, I can open the website from my phone and it works fine.

**Comment by Holzhaus** [comment]
> Maybe there is some caching going on? When I `make html` locally then cd to `build/html` and run `python -m http.server`, I can open the website from my phone and it works fine.

Yup, my changes don't show up on my phone: http://downloads.mixxx.org/builds/manual/prs/PR96/en/_static/js/widget-sidebar.js

For some reason the do on my laptop/desktop.

**Comment by Holzhaus** [comment]
Merge?

**Comment by Holzhaus** [comment]
Looks like the caches expired, it works on my phone now. Merge?

**Comment by daschuer** [comment]
I can now see the language and the PDF download section. Thank you.

**Pull request merged**
