### PR TITLE
Behringer DDM4000: add details about buggy EQ button LEDs

### PR DESCRIPTION
**Pull request by git-developer**

### CODE REVIEW

**Comment by ronso0** [comment]
LGTM

Btw I didn't spot the DDM4000 in the manual right away because "Digital Pro Mixer" is squeezed in between Behringer and DDM4000. The offical product name is DDM4000. It's only the first paragrapher on the product website that mentions "DIGITAL PRO MIXER"

**Comment by git-developer** [comment]
> The offical product name is DDM4000

I'm not really sure if this is _correct_ because the term is scattered in the hardware manuals (including headings), but at least it's not _consistent_ with the Mixxx manual - and I don't like it either ;) - so I removed it.

**Comment by git-developer** [comment]
BTW, the same applies for the terms
* _B-Control_ for [BCR2000](https://www.behringer.com/behringer/product?modelCode=P0245)
* _B-Control Deejay_  for [BCD2000](https://www.behringer.com/behringer/product?modelCode=P0234) and [BCD3000](https://www.behringer.com/product.html?modelCode=P0758)

I can open another PR to remove that, just let me know.

**Comment by ronso0** [comment]
please fix the remaining pre-commit issues then we can merge.

**Comment by git-developer** [comment]
`pre-commit` against `2.3` didn't show any differences; I had to use `2.2` as reference first and then once again `2.3`. I don't understand that.

**Comment by ronso0** [comment]
now unrelated Hercules MP3 e2 files are touched.
If it's not demanded too much could you strip this PR so there are only two commits (based on current 2.3):
* ddm4000 LED fix (incl. ddm4000 pre-commit fixes)
* ddm4000 shorten name

I'm not a rebase pro so personally I would start another branch off 2.3, cherry-pick the relevant commits, manually run pre-commit on the touched files after each commit (and --amend).
Then swap the branches locally and force-push.
Anyone has better instructions?

**Comment by git-developer** [comment]
pre-commit is complaining about the hercules files that are not touched (compared to 2.3). That doesn't happen locally. Can I do something about that?

**Comment by ronso0** [comment]
I don't know...
well, then let's include it here.
CI says:
"If you are seeing this message in CI, reproduce locally with: `pre-commit run --all-files`."
Then just add that as a commit here. :shrug:

**Comment by git-developer** [comment]
Now the branch contains the same as before the rebase, including the hercules files. The pre-commit won't succeed otherwise.

**Comment by git-developer** [comment]
Seems to me that in https://github.com/mixxxdj/manual/pull/387#issuecomment-926948632 something went wrong.

**Comment by ronso0** [comment]
LGTM, thanks!

**Pull request merged**
