### PR TITLE
Build on Travis and deploy to Netlify

### PR DESCRIPTION
**Pull request by Holzhaus**

### CODE REVIEW

**Comment by Be-ing** [comment]
Why is this PR still marked as a draft? Is there something left to do?

**Comment by Holzhaus** [comment]
No, not really, except enabling Travis and Netlify for this repo.

**Comment by Holzhaus** [comment]
It works for my personal repo: https://app.netlify.com/sites/holzhaus-mixxx-manual/overview

**Comment by Be-ing** [comment]
> No, not really, except enabling Travis and Netlify for this repo.

@daschuer or @ywwg can you take care of that?

**Comment by daschuer** [comment]
What exactly need to be done? I think I have no Netifly access yet.

**Comment by daschuer** [comment]
Ok, I have installed Netifly. I expect you need to force push to see it, right?

**Comment by Holzhaus** [comment]
I need to push changes. I'm currently testing a small improvement that allows PR previews for the manual on my private repo. I'll push that here when it works, then this will trigger a build. However, this will only work when Travis is enabled for this branch, too.

**Comment by Holzhaus** [comment]
Ok, I think this is ready now. This builds the full manual including all versions and PDFs on Travis CI (because the netlify allows only 15 minutes per build which does not suffice).


What this does:
- When your push to one of the `manual-A.B.x` branches, it triggers a full manual rebuild on Travis CI. The results are pushed to Netlify production. It always checks out the latest `manual-A.B.x` branch (`manual-2.3.x` at the moment) and builds from there to ensure that the latest sphinx config is used. [^1]
- When you open a PR, it builds this version of the manual in english (but no other version/languages) as a deploy preview. That way you can preview PRs and check if the markup is correct, etc.
- Netlify builds are disabled for the production branch.

[^1] We need to merge the latest state of the `manual-2.2.x` into `manual-2.3.x` for this to work correctly. See https://github.com/mixxxdj/manual/pull/108

**Comment by daschuer** [comment]
I have enabled the Travis web hook.
Not sure if this is sufficient.

**Comment by Be-ing** [comment]
Looks like it is working https://deploy-preview-113--mixxx-manual.netlify.app/

@Holzhaus go ahead and merge if you think it's ready.

**Comment by Be-ing** [comment]
After we merge this, we could automate builds of the application to fetch the latest build of the manual.

**Comment by Holzhaus** [comment]
> @Holzhaus go ahead and merge if you think it's ready.

If we merge now we can use netlify for branch previews, but the Travis Deployment won't work properly because a) the multiversion stuff is missing from the `manual-2.3.x branch` until we merge #108 and also we need to configure the secret deploy key on Travis to give it permission to push a deployment to netlify.

> builds of the application

For packaging the PDF with the executable?

**Comment by Holzhaus** [comment]
> we need to configure the secret deploy key on Travis to give it permission to push a deployment to netlify

OK I just took care of that. So now we need to merge #108 and this is good to go.

**Pull request merged**
