### PR TITLE
Transiflex pull

### PR DESCRIPTION
**Pull request by daschuer**
I have "just" pulled the translations from Transiflex. Since we have not yet translations for our branches, I have pulled it into our stable branch, hoping that this is correct. The source files on Transiflex are heavily outdated anyway. 

Paralled I have created a new Transiflex project only for our 2.3 branch. This is a topic for the a follow up PR.

### CODE REVIEW

**Comment by daschuer** [comment]
The translated deploy review does not work, this the same for all other PRs.

**Comment by Swiftb0y** [comment]
sphinx gets confused for me locally because of the `zh-cn` locale. I guess this is an upstream issue?
> WARNING: reading error: /tmp/tmp5z6jlubg/a41356983fcd7ac78b3f73daed0f5c5a7d181d6d/source/locale/zh-TW/LC_MESSAGES/index.po, expected only letters, got 'zh-tw'

**Review by Swiftb0y — APPROVED** [review]

**Comment by Swiftb0y** [comment]
Sure....

**Comment by daschuer** [comment]
Thank you.

**Pull request merged**
