### PR TITLE
update/add some library icons

### PR DESCRIPTION
**Pull request by ronso0**
Some icons were missing or outdated, e.g. Computer and Tracks

I'm not familiar with translations. Are the po files auto-update or do I need to mass-replace the `ic_lib_*` strings myself?

### CODE REVIEW

**Comment by ronso0** [comment]
_ping_ Easy to review, just skim trough https://deploy-preview-494--mixxx-manual.netlify.app/chapters/library.html and check all icons match those in Mixxx

**Comment by Swiftb0y** [comment]
Screenshot from 2022-08-21 18-06-52
My AutoDJ icon looks different. Icons otherwise match.

**Comment by ronso0** [comment]
> Screenshot from 2022-08-21 18-06-52 My AutoDJ icon looks different (head is square instead of round). Icons otherwise match.

Good catch! updated that..

**Review by Swiftb0y — APPROVED** [review]
Great. LGTM. Would you mind squashing before we merge?

**Comment by ronso0** [comment]
> Great. LGTM. Would you mind squashing before we merge?

Done, ready to roll

**Comment by Swiftb0y** [comment]
Thanks.

**Pull request merged**
