### PR TITLE
Added a link to glossary term: "crossfader" section 2.4.1

### PR DESCRIPTION
**Pull request by julihdez**

### CODE REVIEW

**Comment by ronso0** [comment]
the pre-commit checks fail due to a trailing whitespace (not from your commit though).
this was fixed upstream just now, so to fix this fetch & merge manual-2.2.x
Please also install our pre-commit hooks to check for such errors before commiting:
after `pip install -r requirements.txt`
`pre-commit install`

**Comment by julihdez** [comment]
Hi Ronso0, I already fetched and merged the branch and also installed de pre commit hook but I don't know how to correct this PR, do I need to close it and make a new one with the correction? Thank you

**Comment by Holzhaus** [comment]
No. Push your branch, then the issues will be resolved.

**Comment by julihdez** [comment]
> No. Push your branch, then the issues will be resolved.

Thanks!!

**Comment by deborahtrez** [comment]
Hi @julihdez I have had this problem before. You still have the trailing white spaces. May i offer some assistance? (The bug is not as complicated as it looks 😉)
What code editor are you using? VSCode?

**Review by Holzhaus — APPROVED** [review]
Pre-commit issue is unrelated. LGTM.

**Pull request merged**
