### PR TITLE
Appendix fixes

### PR DESCRIPTION
**Pull request by Holzhaus**

### CODE REVIEW

**Comment by ronso0** [comment]
merge mixxxdj:manual-2.2.x for the preview? I'm lazy today..

**Comment by Holzhaus** [comment]
> merge mixxxdj:manual-2.2.x for the netlify preview? I'm lazy today..

Done.

**Comment by ronso0** [comment]
Thank you, LGTM!

What do you think about replacing `left`/`right` with respective arrows?
image
icons are perceived fater than strings, also it helps  reducing the horizontal size of the table a bit.
icons I used:
https://unicode-table.com/en/1F81C/

**Comment by Holzhaus** [comment]
> Thank you, LGTM!
> 
> What do you think about replacing `left`/`right` with respective arrows?
> image
> icons are perceived fater than strings, also it helps reducing the horizontal size of the table a bit.
> icons I used:
> https://unicode-table.com/en/1F81C/

I did that, but they didn't show up for me. Maybe my default font is lacking the symbol? I reverted the change. Feel free to retry in a follow up PR.

**Comment by ronso0** [comment]
Alright, thanks for checking.

**Pull request merged**
