### PR TITLE
Netlify: Add security headers

### PR DESCRIPTION
**Pull request by Holzhaus**
Please check if everything (search, etc) still works as expected.

Zulip discussion: https://mixxx.zulipchat.com/#narrow/stream/109121-core-team/topic/HTTPS.20on.20downloads.2Emixxx.2Eorg/near/215163005

### CODE REVIEW

**Comment by ronso0** [comment]
with the preview:
- internal links work
- searching any term hangs with `Searching...` forever

**Comment by Holzhaus** [comment]
> * searching any term hangs with `Searching...` forever

Unfortunately, the RTD theme doesn't support plain `script-src: 'self'` in the CSP header :( https://github.com/readthedocs/sphinx_rtd_theme/issues/817

I added some additional script hashes to the header as a workaround.

**Comment by ronso0** [comment]
Jep, search is working again.
Ready for merge?

**Comment by Holzhaus** [comment]
Yes.

**Pull request merged**
