### PR TITLE
 reasonable order for chapters in 3.2. The Mixer Section #286

### PR DESCRIPTION
**Pull request by deborahtrez**
.....just continuing with what @hannydevelop had started in this PR here https://github.com/mixxxdj/manual/pull/286#
.  Hi @ronso0 kindly review :)
@ywwg

### CODE REVIEW

**Comment by ronso0** [comment]
Thank you for picking this up!

Please take a look at [headphone-and-master-mix-controls](https://deploy-preview-337--mixxx-manual.netlify.app/chapters/user_interface.html#headphone-and-master-mix-controls) and try to arange the descriptions in the order the controls appear in the screenshots (left>right).
Also [channel-faders-and-level-meters](https://deploy-preview-337--mixxx-manual.netlify.app/chapters/user_interface.html#channel-faders-and-level-meters) doesn't really match the screenshot.

With those changes I think we can merge this and continue in another PR.

**Comment by deborahtrez** [comment]
> Thank you for picking this up!
> 
> Please take a look at [headphone-and-master-mix-controls](https://deploy-preview-337--mixxx-manual.netlify.app/chapters/user_interface.html#headphone-and-master-mix-controls) and try to arange the descriptions in the order the controls appear in the screenshots (left>right).
> Also [channel-faders-and-level-meters](https://deploy-preview-337--mixxx-manual.netlify.app/chapters/user_interface.html#channel-faders-and-level-meters) doesn't really match the screenshot.
> 
> With those changes I think we can merge this and continue in another PR.

You're welcome. Let me get started on that right now.

**Comment by deborahtrez** [comment]
> Please take a look at [headphone-and-master-mix-controls](https://deploy-preview-337--mixxx-manual.netlify.app/chapters/user_interface.html#headphone-and-master-mix-controls) and try to arange the descriptions in the order the controls appear in the screenshots (left>right).

Hey @ronso0  before i start, i would like to know if this matching is correct. 
**Controls** --------vs--------  **Description in manual**
Head Mix------------------Pre/ Main knob
Head ----------------------Head Gain
Split Cue -------------------Head Split Button
Balance --------------------Balance Knob
Master -------------------- Master Knob
Booth --- (there is no description for this control....?)

**Comment by ronso0** [comment]
You're right, let's use the terms used in Deere:

> **Controls** --------vs-------- **Description in manual**
> Head Mix------------------Pre/ Main knob > **Head Mix knob**
> Head ----------------------Head Gain > **Head knob**
> Split Cue -------------------Head Split Button > **Split Cue button**
> Balance -------------------- **Balance knob** 
> Master -------------------- **Master knob**



> Booth --- (there is no description for this control....?)

That is shown only if the respective output device is configured in Preferences > Sound Hardware

**Comment by deborahtrez** [comment]
Hey @ronso0 this is ready for your review :)

**Comment by ronso0** [comment]
thanks, LGTM
@hozhaus Wanny take another look?

**Pull request merged**
