### PR TITLE
fix(changelog): workaround changelog entries causing build errors

### LINKED ISSUE #553: mixbot writes corrupt changelog.rst files, which let Sphinx / Build Check fail and inhibits generation of preview
How can we prevent, that mixbot can commit files, that break builds of HEAD?
https://github.com/mixxxdj/manual/actions/runs/4378433738/jobs/7665114625?pr=550

### PR DESCRIPTION
**Pull request by Swiftb0y**
Fixes #553

Somewhat dirty workaround but good enough I think. wdyt?

### CODE REVIEW

**Comment by JoergAtGithub** [comment]
The underscore suffix looks wrong, but Sphinx currently fails because we have the link name multiple times:
`Warning: /home/runner/work/manual/manual/source/chapters/appendix/changelog.rst:10: WARNING: Duplicate explicit target name: "#11460"`
https://github.com/mixxxdj/manual/blob/66b9ebee8eeaf42d4dc3d800bab6b925865dafcd/source/chapters/appendix/changelog.rst?plain=1#L550-L556

**Comment by Swiftb0y** [comment]
Yeah, thats because each of those links creates a target and there can't be multiple of them. This duplicates the underscore at the end, which will result in anonymous references, which won't create a target and thus the link text is irrelevant. The build failed previously, because the base commit was outdated.

**Comment by Swiftb0y** [comment]
all green. finally

**Comment by JoergAtGithub** [comment]
Thanks for the explanation. This makes sense to me! Thank you!

**Comment by Swiftb0y** [comment]
Thank you.

**Pull request merged**
