### PR TITLE
Native Instruments Traktor Kontrol S2 MK2: Fix markup

### PR DESCRIPTION
**Pull request by Holzhaus**
I noticed that this was broken.

### CODE REVIEW

**Comment by ronso0** [comment]
LGTM. But wh is the table header so unnecessarily tall?
image

**Comment by ronso0** [comment]
the `control` style is inconsistent:
image

**Comment by ronso0** [comment]
> LGTM. But wh is the table header so unnecessarily tall?
> image

Aaah, the reason is that header strings are inserted as `p`:
image

**Comment by Holzhaus** [comment]
> > LGTM. But wh is the table header so unnecessarily tall?
> > image
> 
> Aaah, the reason is that header strings are inserted as `p`:
> image

I think that is indended by the theme and helps highlighting the table.

**Comment by ronso0** [comment]
but it doesn't add value. Headers are bold and thus distinguishable already.
But no real issue right now. I postpone that to when we polish the styles in general.

**Comment by Holzhaus** [comment]
> the `control` style is inconsistent:
> image

I don't want to hardcode the font family right now. I think it's better to avoid using `:hwlabel` in headlines anyway. Fixed in https://github.com/mixxxdj/manual/pull/264/commits/6c28993456844189a31fb38a7b8cb2d51bd5d2b1.

**Comment by ronso0** [comment]
Yup, that what I meant.

LGTM

**Pull request merged**
