### PR TITLE
Sphinx link check fix 

### PR DESCRIPTION
**Pull request by daschuer**
This fixes some links and put the rest to linkcheck_ignore. This way we get rid of the permanent failing CI.
The pre-commit failure is fixed here: https://github.com/mixxxdj/manual/pull/482

### CODE REVIEW

**Comment by Swiftb0y** [comment]
Can you rebase now that #482 has been merged?

**Comment by daschuer** [comment]
Done

**Comment by Swiftb0y** [comment]
Thank you. We should documents somewhere that authors need to fixup anchors on github wikis.

**Comment by Holzhaus** [comment]
> Thank you. We should documents somewhere that authors need to fixup anchors on github wikis.

Or even better, we could make a little script that auto-replaces the anchors and add that as a pre-commit hook.

For reference, I documented the Shell commands i used for bulk replacing the anchors in the commit messages back then (https://github.com/mixxxdj/manual/pull/300/commits/71916cdf033a17db4cb4a0c8e12055b7a4bb3993), but I suppose Python script would be preferable so that it also works for Windows users.

**Comment by Swiftb0y** [comment]
> Or even better, we could make a little script that auto-replaces the anchors and add that as a pre-commit hook.

I agree, but I didn't want the scope of this PR to grow ten-fold.

**Comment by Holzhaus** [comment]
Ah, I took your comment as a general recommendation, not a request to add documentation as part of this PR.

**Comment by Swiftb0y** [comment]
I went ahead and implemented the auto-fixup myself. I've never implemented a pre-commit hook, also my python is a bit dusty. I'd appreciate a thorough review. daschuer/manual#4

**Comment by daschuer** [comment]
The script is merged. Thank you @Swiftb0y. 
Can we merge this now?

**Comment by daschuer** [comment]
You part has been reviewed by me and Jan, so I think the second pair of eyes rules is fulfilled if you just press merge.

**Pull request merged**
