### PR TITLE
Update index.rst

### PR DESCRIPTION
**Pull request by aishagurung**
grammar fix and used more decriptive language

### CODE REVIEW

**Comment by ronso0** [comment]
@aishagurung Why did you close this? The changes are valid, it just requires a native speaker to approve.
@Be-ing @ywwg

**Comment by ywwg** [comment]
Sorry for the lack of review -- this change looks ok but it is target 2.2, which is an old version. If you'd still like to work on this please reopen! @aishagurung

**Comment by aishagurung** [comment]
@ronso0 @ywwg I decided to add a table for the feature list with added descriptions as it looks a bit off the way it is .

**Comment by ywwg** [comment]
ok! just be sure to @ me when you want a review

**Pull request closed without merging**
