### PR TITLE
sphinx-mixxx: Fix usage of ampersand in hwlabel role

### PR DESCRIPTION
**Pull request by Holzhaus**

### CODE REVIEW

**Comment by ronso0** [comment]
I'm a python noob..
Where is this used so i can visually compare before/after?
I went through those 4 controllers
image

**Comment by Holzhaus** [comment]
Use an ampersand (&) inside a hwlabel.

Before, the ampersand was interpreted as mnemonic (like in guilabel), and to get an actual ampersand character to show up you had to escapte it by using && instead of &.

This just removes that behaviour by subclassing `SphinxRole` directly instead of `GUILabel`.

**Comment by Holzhaus** [comment]
This issue was discovered here: https://github.com/mixxxdj/manual/pull/130#discussion_r512482522

**Comment by ronso0** [comment]
the & still needs to be surrounded by whitespaces for this to work:
image

**Comment by Holzhaus** [comment]
> the & still needs to be surrounded by whitespaces for this to work:
> image
> 

Did you upgrade the `sphinx-mixxx` package? Run `pip install -r requirements.txt`.

**Comment by ronso0** [comment]
ah okay, `**pip3** install -r requirements.txt` and now it looks as intended.
Thanks!

**Pull request merged**
