### PR TITLE
[Xone K2] Fix formatting

### PR DESCRIPTION
**Pull request by sven-frotscher**
The nested list items weren't indented.

### CODE REVIEW

**Review by ronso0 — APPROVED** [review]
Thank you, this LGTM

**Comment by ronso0** [comment]
Thank you for this contribution!

Updates should go to the branch that corresponds to the mixxx branch that contains the mapping.
In this case the mapping itself was last changed 3 years ago, so it's definitely in Mixxx 2.3.
Please rebase onto `2.3`, force-push. I already changed the target branch here.

Rebasing this single commit should be as easy as
`git rebase -i [mixxx remote]/2.3` where [mixxx-remote] is the name you gave to the mixxx remote repo.
If you have any questions don't hesitate to ask.

**Comment by sven-frotscher** [comment]
Like this? It required some jumping through hoops since I originally made the edit on GitHub, not locally.

**Comment by ronso0** [comment]
Yup, looks good. Thank you!

**Pull request merged**
