### PR TITLE
Add :hwlabel: role

### PR DESCRIPTION
**Pull request by Holzhaus**
Based on #151.

### CODE REVIEW

**Comment by Holzhaus** [comment]
Let me know what you think: https://deploy-preview-224--mixxx-manual.netlify.app/hardware/controllers/roland_dj_505.html

**Comment by ronso0** [comment]
Looks good!
image

**Comment by Holzhaus** [comment]
Ready to merge?

**Comment by ronso0** [comment]
Even though the preview looks good I'm having trouble to build it locally now:
`source/hardware/controllers/roland_dj_505.rst:61: WARNING: Unknown interpreted text role "hwlabel".`

**Comment by Holzhaus** [comment]
You need to install the `sphinx-mixxx` extension. Run `pip install -r requirements.txt`.

**Comment by ronso0** [comment]
Yes, no it works. LGTM!

**Pull request merged**
