### PR TITLE
Fix Scrollbar in tables and prevent wrapping in :hwlabel:

### PR DESCRIPTION
**Pull request by Holzhaus**

### CODE REVIEW

**Comment by ronso0** [comment]
now the hwlable roles are gone, some entirely like Shift in the first paragraph:
image

#264 :
image

**Comment by ronso0** [comment]
Could you now merge 2.3 so the preview is updated?

**Comment by Holzhaus** [comment]
@ronso0 This is a different PR and unrelated to the S2MK2 fixes (and the branch is not based on them). This fixes the scrollbar issue in tables (reported in #97):

Before: https://manual.mixxx.org/2.3/en/hardware/controllers/roland_dj_505.html#browser-section-p-4
After: https://deploy-preview-265--mixxx-manual.netlify.app/hardware/controllers/roland_dj_505.html#browser-section-p-4

**Comment by ronso0** [comment]
ah ok, I got confused.

**Comment by ronso0** [comment]
LGTM

**Pull request merged**
