### PR TITLE
Library, Track menu: add some newlines to have consistent header styles

### PR DESCRIPTION
**Pull request by ronso0**
before
image

now
image

### CODE REVIEW

**Comment by ronso0** [comment]
will removing colons break translations?
if so I can revert the changes.

**Comment by ronso0** [comment]
seems it doesn't: latest translations for French (100% translated) are from early 2020 IINM

**Comment by ronso0** [comment]
_ping_

**Review by Holzhaus — APPROVED** [review]
LGTM, thank you. Should this be merged now? If so, please remove the draft status.

**Comment by ronso0** [comment]
thx, ready.

**Comment by ronso0** [comment]
ping, pong..

**Pull request merged**
