### PR TITLE
Document Rekordbox library import

### PR DESCRIPTION
**Pull request by deborahtrez**
With reference to this issue, https://github.com/mixxxdj/manual/issues/157. There was missing documentation about importing rekordbox libraries from rekordbox prepared devices into Mixxx.

 I documented this here. Ready for review.
@ywwg

### CODE REVIEW

**Comment by deborahtrez** [comment]
Hi @Be-ing @Holzhaus @ywwg , this PR is ready for your review.

**Comment by ywwg** [comment]
In the future, you can click the gear in the Review area in the upper right to request a review:
image

**Comment by ywwg** [comment]
it looks like there are extra differences between your code and mixxx.  Do you know how to merge in changes from 2.3 (using git fetch, git merge, or git pull)?

**Comment by Holzhaus** [comment]
I think 54c40dbba7cdda9a296fbf835f2b38194510cd2f is the issue. Please always use `git pull upstream <branch>` to merge changes from upstream an leave the commit message as is.

Please run:

    git fetch upstream
    git rebase upstream/2.3

And remove everything except the relevant commit in this branch (i. e. The last two commit lines).

**Comment by deborahtrez** [comment]
> I think [54c40db](https://github.com/mixxxdj/manual/commit/54c40dbba7cdda9a296fbf835f2b38194510cd2f) is the issue. Please always use `git pull upstream <branch>` to merge changes from upstream an leave the commit message as is.
> 
> Please run:
> 
> ```
> git fetch upstream
> git rebase upstream/2.3
> ```
> 
> And remove everything except the relevant commit in this branch (i. e. The last two commit lines).

Okay. I have run these two commands but it seems `git rebase` requires me to resolve merge conflicts. Same with `git revert` (as i was reverting the last two commits). Resolving merge conflicts is what created the extra differences between my code and mixxx's.  
Should I accept all current changes?

image

**Comment by deborahtrez** [comment]
`git revert -m 1 54c40db` returned 

image

**Comment by Holzhaus** [comment]
Don't run git revert. You want to keep the last two commits, not revert them.

The issue is that the second to last commit also makes unrelated changes in other files, and these conflict.
Therefore, you need to resolve these conflicts by running `git mergetool` after running `git rebase`. After resolving the conflicts, you can do `git rebase --continue`.

**Comment by deborahtrez** [comment]
> In the future, you can click the gear in the Review area in the upper right to request a review:
> image

Hi @ywwg there is no gear icon on my side. I think it because I don't have the required permissions.

image

**Comment by deborahtrez** [comment]
Hi @Holzhaus @ywwg . I felt that this branch would take me more time than necessary to fix. So I have created a new PR for this in #322 . With just the one commit for documenting the rekorbox library import.

**Pull request closed without merging**
