### PR TITLE
Deploy Travis-built PDFs to https://downloads.mixxx.org/builds/manual/.

### PR DESCRIPTION
**Pull request by rryan**
Copies PDFs built by Travis to
[`https://downloads.mixxx.org/builds/manual/<branchname>/`](https://downloads.mixxx.org/builds/manual), replacing all
existing files on each build.

Due to #273, I disabled the actual PDF build until we can work out why it's failing.

TESTED:
* https://travis-ci.org/github/mixxxdj/manual/builds/740535870

### CODE REVIEW

**Comment by Be-ing** [comment]
https://downloads.mixxx.org/builds/manual/manual-travis-deploy/
The files are 0 bytes.

**Comment by rryan** [comment]
> https://downloads.mixxx.org/builds/manual/manual-travis-deploy/
> The files are 0 bytes.

Yea, see description: `Due to #273, I disabled the actual PDF build until we can work out why it's failing.` and discussion:
https://mixxx.zulipchat.com/#narrow/stream/109176-documentation/topic/manual.20deploy.20to.20downloads.2Emixxx.2Eorg

**Comment by rryan** [comment]
#275 fixes the PDF build.

**Comment by Holzhaus** [comment]
@rryan Do you want to rebase on the latest changes or should I take care of that?

**Comment by rryan** [comment]
> @rryan Do you want to rebase on the latest changes or should I take care of that?

Done -- though I believe as is both the main branch and manual-2.3.x branch are deploying the main branch's code because the before_script re-clones the repo and checks out the `main` branch. Commented here:
https://github.com/mixxxdj/manual/commit/94c20bb93d3a14b4a21e78f1393bda8ca80b5231

**Comment by rryan** [comment]
> Done -- though I believe as is both the main branch and manual-2.3.x branch are deploying the main branch's code because the before_script re-clones the repo and checks out the `main` branch. Commented here:
> [94c20bb](https://github.com/mixxxdj/manual/commit/94c20bb93d3a14b4a21e78f1393bda8ca80b5231)

Fixed.

**Review by Holzhaus — APPROVED** [review]
LGTM, thank you!

**Pull request merged**
