### PR TITLE
Broken links 2.2

### PR DESCRIPTION
**Pull request by Holzhaus**

### CODE REVIEW

**Comment by ronso0** [comment]
the link check fails for https://www.streamfinder.com/

**Comment by Holzhaus** [comment]
Site seems to be down. Weird, didn't fail half an our ago. Maybe they have server problems?

**Comment by ronso0** [comment]
oki. I'll merge and we'll see if it fails in the next PRs.

**Comment by Holzhaus** [comment]
i'll take care of the conflicts when merging into 2.3

**Pull request merged**
