### PR TITLE
Mixxxcontrol improvements

### PR DESCRIPTION
**Pull request by Holzhaus**

### CODE REVIEW

**Comment by ronso0** [comment]
The NOTEs appear quite heavy within that rather compact controls list and becomes visually more important than the control itself.
Can we simply add the note to the control description?

**Comment by Holzhaus** [comment]
Ok, ready to review and merge!

**Comment by ronso0** [comment]
I spotted some references to `master`. In LateNight #3234 I changed the mixer labels to `Main`, but I guess we should stick to Master here where it references the `[Master]` group to avoid confusion.
We may change that to Main later on when we have a way to alias entire groups.
https://mixxx.zulipchat.com/#narrow/stream/247620-development-help/topic/simplifying.20Mic.20CO's

**Comment by ronso0** [comment]
LGTM, thanks!

**Pull request merged**
