### PR TITLE
Document intro and outro markers

### PR DESCRIPTION
**Pull request by Goodiec**
This a pull request for this issue - https://github.com/mixxxdj/manual/issues/146
Kindly review

### CODE REVIEW

**Comment by Holzhaus** [comment]
Please fetch the latest state from upstream and rebase on `upstream/manual-2.3.x` to fix the issues (not your fault, these existed in manual-2.3.x).

**Comment by Goodiec** [comment]
> Please fetch the latest state from upstream and rebase on `upstream/manual-2.3.x` to fix the issues (not your fault, these existed in manual-2.3.x).

Okay, let me try that. Thank you

**Comment by Holzhaus** [comment]
No, I meant rebasing:

```
git remote add upstream https://github.com/mixxxdj/manual.git
git fetch upstream
git rebase upstream/manual-2.3.x
```

**Comment by Goodiec** [comment]
> No, I meant rebasing:
> 
> ```
> git remote add upstream https://github.com/mixxxdj/manual.git
> git fetch upstream
> git rebase upstream/manual-2.3.x
> git push -f origin manual-2.3.x
> ```

Says everything is up to date

**Comment by Goodiec** [comment]
I'll close this and refork the repository

**Comment by Holzhaus** [comment]
No, that is not necessary.

**Pull request closed without merging**
