### PR TITLE
remove mention of double-bpm detection, which has been removed

### PR DESCRIPTION
**Pull request by ywwg**

### CODE REVIEW

**Comment by esbrandt** [comment]
It's been a while since the PR was submitted.
My guess is double-bpm detection has not returned until?

**Comment by rryan** [comment]
@ywwg this change still good?

**Comment by daschuer** [comment]
This has not been removed. We can close this PR.

**Comment by daschuer** [comment]
This was one of the rare cases where the "close and comment" button was helpful :-/

**Comment by ywwg** [comment]
yup, we left the feature in

**Pull request closed without merging**
