### PR TITLE
Bump latest released version to 2.3

### PR DESCRIPTION
**Pull request by Holzhaus**

### CODE REVIEW

**Comment by daschuer** [comment]
Do we want to fix the broken link before?

**Comment by Holzhaus** [comment]
We can remove it. Looks like banshee is no more: https://github.com/BansheeMediaPlayer/BansheeMediaPlayer.github.io/commit/28e58359113012bc5b34aec8fac7d212b123b71e#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051R24

**Comment by Holzhaus** [comment]
Ah, website is here: https://bansheemediaplayer.github.io/

**Review by daschuer — APPROVED** [review]
Ready for release .. :-)

**Comment by Holzhaus** [comment]
Oh, this was merged prematurely. 2.3 builds of the mixxxdj/mixxx repo fail :(

**Comment by daschuer** [comment]
What fails? There was only the missing banshee link.

**Comment by Holzhaus** [comment]
Not in this repo, in the actual mixxx repo. But it doesn't matter, these change don't apply anyway unless it's merged to `main`.

**Pull request merged**
