### PR TITLE
Update 2.2.x version history

### PR DESCRIPTION
**Pull request by Holzhaus**
A few unrelated commits in here because I merged manual-2.1.x into manual-2.2.x first.

### CODE REVIEW

**Comment by Holzhaus** [comment]
@ronso0 merge?

**Comment by ronso0** [comment]
@Holzhaus there are conflicts now after the recent merges.

**Comment by Holzhaus** [comment]
Weird, I don't see them: 
Screenshot_20201007_192718_com duckduckgo mobile android

**Comment by ronso0** [comment]
image
Don't know what's wrong.

**Comment by Holzhaus** [comment]
Is this PR okay OK to merge? I could just hit merge here and we'll see what happens ☠️

**Comment by Holzhaus** [comment]
Ah, just probably switched the merge strategy from "create merge commit" to "rebase". For the manual this is probably okay, but don't do that for actual code as it creates new, untested commits. As a small (and insufficient) safety measure to avoid broken commits, GitHub seems to refuse to rebase if changes occurred in the same file, even though git's automatic conflicts resolution could handle it.

**Comment by ronso0** [comment]
> Ah, you probably switched the merge strategy from "create merge commit" to "rebase".

Naa, didn't do that consciously, maybe it was adapted frmo another PR?
Simple merge works.
LGTM!

**Pull request merged**
