### PR TITLE
keyboard shortcuts sheet: add maximize_library

### PR DESCRIPTION
**Pull request by ronso0**
image

### CODE REVIEW

**Review by daschuer — APPROVED** [review]
LGTM, Thank you.

**Comment by daschuer** [comment]
The broken links are unrelated.

**Comment by daschuer** [comment]
Do you want to update: 
chapters/appendix/keyboard_mapping_table.rstl as well?

**Comment by ronso0** [comment]
sure.
though it's not clear what that table is for: it has some overlap with the (deck & AutoDJ) mapping graphic but also contains snippets from the app shortcuts (vinyl control). So there are essentially 3 different mapping sheets.

We should find a smart way to re-arrange those, like 
* add a second view to the graphical sheet (app shortcuts) > Help menu + manual "Controlling Mixxx"
* consolodiate the tables (app table + deck/AutoDJ table) to have a textual, screen-reader-accessible representation
* tweak the tables to have only 3 columns

**Comment by ronso0** [comment]
https://github.com/mixxxdj/manual/issues/405

**Comment by daschuer** [comment]
Thank you for the extra commit and the bug report.

**Pull request merged**
