### PR TITLE
Document the Traktor Kontrol S3 FX changes

### PR DESCRIPTION
**Pull request by robbert-vdh**
These are the manual changes accompanying https://github.com/mixxxdj/mixxx/pull/11199. I split up the effects section to cover both modes, and I've moved the FX knob behavior for 'filter mode' to the new Multi Effect mode sections. I went with Quick Effect Mode and Multi Effect Mode for the time being because naming things is difficult!

It might also be nice to link to some suitable quick effect chain presets on the manual page.

### CODE REVIEW

**Comment by robbert-vdh** [comment]
By the way, both of these PRs assume https://github.com/mixxxdj/mixxx/pull/11198 has been merged. If that situation changes or if https://github.com/mixxxdj/mixxx/pull/4687 can do the trick instead (it did not yet work when I tried it) then this and the comments in the script need to be amended.

**Comment by ronso0** [comment]
> It might also be nice to link to some suitable quick effect chain presets on the manual page.

Yeah. Linking to a forum thread would be okay I'd say.

**Comment by ronso0** [comment]
after 2.3 has been merged into 2.4 pre-commit should work again.

**Comment by JoergAtGithub** [comment]
Could you please merge upstream/2.4. This should fix the CI fails and generate the preview.

**Comment by robbert-vdh** [comment]
Done. Sorry it took so long, had a busy couple weeks!

**Comment by Swiftb0y** [comment]
Broken links come from www.keithmcmillen.com
As far as I can tell from the webarchive, the site doesn't seem to be abandoned, maybe we should just wait a little?

**Comment by JoergAtGithub** [comment]
Could you please commit a dummy change to trigger the Preview generation.

**Comment by robbert-vdh** [comment]
@JoergAtGithub I rebased on top of the new 2.4 branch.

**Comment by Swiftb0y** [comment]
Deploy failed because the nodejs download servers 500'd. The retried build unfortunately doesn't show in the github UI. The deploy preview for 06c0aaf can be found at https://644c0b2ed647ff00b334cb21--mixxx-manual.netlify.app/

**Comment by JoergAtGithub** [comment]
Could you please merge upstream/2.4 to fix the CI fails.

**Comment by JoergAtGithub** [comment]
@robbert-vdh I talked to @ywwg and we think the mapping PR https://github.com/mixxxdj/mixxx/pull/11199 can be merged as it is, without waiting for https://github.com/mixxxdj/mixxx/pull/11198.
But we need this manual PR matching to the code. Currently this PR describes the changes of both PRs. Could you please remove the section about the Superknob load preferences, that this manual PR contains only changes implemented in the mapping PR itself.

**Comment by robbert-vdh** [comment]
Should I then document the soft takeover behavior instead? Because soft takeover can be pretty confusing if you're expecting similar behavior to Pioneer/Denon/Traktor/Serato/most other DJ software.

**Comment by JoergAtGithub** [comment]
The documentation must match, what we get, when we only merge the mapping PR. But you don't need to to write down so many details in the mapping documentation.
If we later merge #11198 and/or #4687 we can adjust the documentation accordingly.

**Comment by robbert-vdh** [comment]
I removed the reference to the superknob adoption and I replaced it with a bit describing the soft takeover behavior.

**Comment by JoergAtGithub** [comment]
LGTM! Thank you!

**Pull request merged**
