### PR TITLE
requirements.txt: Remove unneeded fabric/pycrypto/ecdsa dependencies

### PR DESCRIPTION
**Pull request by Holzhaus**

### CODE REVIEW

**Comment by rryan** [comment]
Fabric is still used for maintenance, e.g.
https://github.com/mixxxdj/manual#update-source-translations
and the fabfile.py is still there, so I think it makes sense to keep them in requirements.txt unless you switch to an alternative.

Are you trying to cut down on build time on netlify?

**Comment by Holzhaus** [comment]
Yes. And also this is necessary for https://github.com/mixxxdj/mixxx/pull/3047 because pycrypto takes long to build and causes issues on some systems.

**Comment by rryan** [comment]
> Yes. And also this is necessary for [mixxxdj/mixxx#3047](https://github.com/mixxxdj/mixxx/pull/3047) because pycrypto takes long to build and causes issues on some systems.

How about splitting them into a requirements-dev.txt ?

**Comment by Holzhaus** [comment]
We could, but do we really need fabric? For example, `fab tx_push` is just wrapper for `tx push -s`. I think we can just remove it and update the README with the actual commands.

**Comment by Holzhaus** [comment]
I updated the README. @rryan Please have a look.

**Comment by Holzhaus** [comment]
Merge?

**Comment by Holzhaus** [comment]
Ping

**Comment by Holzhaus** [comment]
@Be-ing Merge?

**Pull request merged**
