### PR TITLE
source/conf.py: Bump latest release version to 2.3

### PR DESCRIPTION
**Pull request by Holzhaus**

### CODE REVIEW

**Review by Swiftb0y — APPROVED** [review]
I have 0 idea how pdf packaging works, but I guess this seems reasonable.

**Comment by Holzhaus** [comment]
This isn't about PDF, it marks 2.3 as latest released version and thus hides the development version note here: https://manual.mixxx.org/2.3/en/index.html

**Comment by esbrandt** [comment]
Please bump the ``Edit on GitHub`` link as well
https://github.com/mixxxdj/manual/blob/23bc5fd01aab8df9dcf6f2b6aa68dfe37c726fc7/source/conf.py#L177

**Comment by Holzhaus** [comment]
> This PR is still marked as `Draft`, any todo left?

well, it should only be merged immediately when actually released 2.3.

**Comment by Holzhaus** [comment]
Already done in #400.

**Pull request closed without merging**
