### PR TITLE
merge 2.2 branch to 2.3 branch

### PR DESCRIPTION
**Pull request by Be-ing**

### CODE REVIEW

**Comment by Holzhaus** [comment]
@Be-ing Can you resolve the merge conflict? Thn we can merge this IMHO.

**Comment by Holzhaus** [comment]
ping

**Comment by Be-ing** [comment]
Ready for merge?

**Comment by Holzhaus** [comment]
Can you undelete `source/_static/Mixxx-220-Keyboard-Mapping.png`? This causes build warnings and the file exists both on the `manual-2.2.x` and `manual-2.3.x` branch at the moment, so I don't think it should be removed.

**Comment by Be-ing** [comment]
I thought it was removed from the 2.3 branch in #109?

**Comment by Holzhaus** [comment]
No idea, but it's still there: https://github.com/mixxxdj/manual/tree/manual-2.3.x/source/_static

**Comment by Be-ing** [comment]
Maybe it was accidentally re-added in a later merge?

**Comment by Holzhaus** [comment]
I don't know but it causes warnings that the file is missing.

**Comment by Be-ing** [comment]
I see the file deleted in #109 was still referenced in the RST. I changed that to reference the SVG image added in #109 and it fixed the warning.

**Comment by Holzhaus** [comment]
Thank you!

**Pull request merged**
