### PR TITLE
Update some ja translations.

### PR DESCRIPTION
**Pull request by chanharabomber**
Hi, 
I tried to translate some sentences in Japanese.
Sorry, I went through the readme but I am not sure how I can contribute translating document, so let me create the PR.
If I do not add new files, can I skip the process of "Push source translations to Transifex"?
(Is this PR process correct?)
I worried about I took a look at the commit log and I cannot find the translating commit itself in commit log.
Please feel free to point out and sorry for taking time to answer this. 

I checked that translations work correctly in my local environment by below commands.
 $ sphinx-intl build
 $ make -e SPHINXOPTS="-Dlanguage=ja" html

Thank you,

### CODE REVIEW

**Comment by daschuer** [comment]
Thank you for the work. We do not commit translations directly into the repository. We upload or edit them directly at https://app.transifex.com/mixxx-dj-software/mixxx-dj-manual-23/language/ja/
I think in this case is would be straight forward to copy and past the translations into the Transiflex GUI. Please ping merge here if your are done and than I can pull the result into the repository.

**Comment by chanharabomber** [comment]
Thank you very much for your comment!
I will update the translation in Transiflex GUI and let you know when finishing update:)
Sorry, I have a quick question about Japanese version in Transiflex GUI.
In manual (legacy, use 2.3) page, there are 2 Japanese tab I can select: "Japanese(Japane)(ja_Jp)" and "Japanese(ja)".
which one should I update?
For example,  in /chapters/controlling_mixxx.pot file,
Japanese(Japane)(ja_Jp) seems to be used for online manual https://manual.mixxx.org/2.3/ja/chapters/controlling_mixxx.html.
But in Japanese(ja), the controlling_mixxx.pot file does not have translations.
So maybe need to update Japanese(Japane)(ja_Jp) version?

**Comment by daschuer** [comment]
You touch a sore point. We have not yet a good process how to regular update the translations. I normally do it when releasing a new version of Mixxx, because it is a bit of work. But we should do it more often. 
So it is OK, to ping me. If you have an idea to improve the process. 
I will fetch your new translations now.

**Comment by daschuer** [comment]
I have now merged this PR and pushed your changes to Transiflex. 
Please verify if that is OK.

**Comment by daschuer** [comment]
> Oh, I'm sorry. I think I should have updated both "Japanese(Japane)(ja_Jp)" and "Japanese(ja)" for now.
Because it seems that Japanese(Japane)(ja_Jp) is used to the current online manual.

We should fix it in the way that (ja) is used.
For now I only see online: 
https://manual.mixxx.org/2.3/ja/
This is not available: 
https://manual.mixxx.org/2.3/ja_Jp

Is this an issue? Do you see the "Page not found" 404.html instead? 
 
> After that, but it says Japanese translated "0%".

Yes it is actually 0.55 %. Probably a rounding bug in the Transifex GUI

> Also the [link](https://app.transifex.com/mixxx-dj-software/mixxx-dj-manual-23/translate/#ja/chapters--controlling_mixxx/435765409?q=text%3A'finger+click+gesture+is+often+treated+as+a+right+click') you kindly share, in this link, I cannot choose any destination languages, it means I cannot edit/translate in this project.

Oh I see. Manual Translation requires to invite and accept users. I have now invited you as translator and also opened the translation for anyone. I hope that works and will not attract spammers.

**Comment by chanharabomber** [comment]
Thank you for reply.

> For now I only see online:
> https://manual.mixxx.org/2.3/ja/
> This is not available:
> https://manual.mixxx.org/2.3/ja_Jp
> Is this an issue? Do you see the "Page not found" 404.html instead?
Yes. I guess there are some potential issues.
First of all, I encountered the same as you explained. 
"manual.mixxx.org/2.3/ja" is available and I've got "Page not found" when I access to "manual.mixxx.org/2.3/ja_Jp".

But the weird thing is that when I go to "manual.mixxx.org/2.3/ja_Jp", it is redirecting to **"https://manual.mixxx.org/2.3/ja/ja_Jp"**. 

Do you think there are any this kind of redirecting settings in Transifex?
Do we expect both "manual.mixxx.org/2.3/ja" and "manual.mixxx.org/2.3/ja_Jp" should work independently?
(This is why I guess that it is not an issue but some potential issues.)

> Yes it is actually 0.55 %. Probably a rounding bug in the Transifex GUI
Oh I got it. Thank you for your information:)

> Oh I see. Manual Translation requires to invite and accept users. I have now invited you as translator and also opened the translation for anyone. I hope that works and will not attract spammers.

Thank you very much! I can access to 2.3 version and edit/translate:) Also I can see the 2.3 ja version is corresponding to the current online manual. I will try to translate some parts.

**Pull request merged**
