### PR TITLE
Reloop Mixage MIDI controller documentation

### PR DESCRIPTION
**Pull request by HorstBaerbel**
Documentation for the Reloop Mixage DJ MIDI controller. Corresponding mixxx mapping pull request is [#10892](https://github.com/mixxxdj/mixxx/pull/10892)

### CODE REVIEW

**Comment by HorstBaerbel** [comment]
Image can be used by permission from Reloop

**Comment by HorstBaerbel** [comment]
I'm not sure why the workflows failed. It looks like a pipeline problem. I tried to built the docs locally using sphinx and it worked fine for me...

**Comment by ronso0** [comment]
> I'm not sure why the workflows failed. It looks like a pipeline problem. I built the docs locally using sphinx and it worked fine for me...

Did you try `make html` and `make pdf`?

**Comment by HorstBaerbel** [comment]
`make html` does build the docs, `make pdf` complains about pdf not being a target. I've run an XML linter and fumbled with the RST until `sphinx-build -W -b html source build/html` succeeded. Everything is fine from my side according to the contribution guide afaik.

The checks seem to fail due to the pipeline / image being broken:

> 5:05:06 PM: Build ready to start
> 5:05:09 PM: build-image version: d7b3dbfb0846505993c9a131894d1858074c90b4 (focal)
> 5:05:09 PM: build-image tag: v4.10.1
> 5:05:09 PM: buildbot version: 37262c48b1f3cfa88c6caed707d29b19aef6a5a7
> 5:05:09 PM: Fetching cached dependencies
> 5:05:09 PM: Failed to fetch cache, continuing with build
> 5:05:09 PM: Starting to prepare the repo for build
> 5:05:09 PM: No cached dependencies found. Cloning fresh repo
> 5:05:09 PM: git clone https://github.com/mixxxdj/manual
> 5:05:16 PM: Preparing Git Reference pull/516/head
> 5:05:17 PM: Parsing package.json dependencies
> 5:05:17 PM: Different publish path detected, going to use the one specified in the Netlify configuration file: 'build' versus '/' in the Netlify UI
> 5:05:17 PM: Different build command detected, going to use the one specified in the Netlify configuration file: 'sphinx-build -b html source build' versus '' in the Netlify UI
> 5:05:18 PM: Starting build script
> 5:05:18 PM: Installing dependencies
> 5:05:18 PM: /opt/build-bin/run-build-functions.sh: line 223: /opt/buildhome/python3.7/bin/activate: No such file or directory
> 5:05:18 PM: Error setting python version from runtime.txt
> 5:05:18 PM: Please see https://github.com/netlify/build-image/blob/focal/included_software.md for current versions
> 5:05:18 PM: Build was terminated: Build script returned non-zero exit code: 1
> 5:05:18 PM: Creating deploy upload records
> 5:05:18 PM: Failing build: Failed to build site
> 5:05:18 PM: Failed during stage 'building site': Build script returned non-zero exit code: 1 (https://ntl.fyi/exit-code-1)
> 5:05:18 PM: Finished processing build request in 9.378486307s

**Comment by HorstBaerbel** [comment]
Please tell my if I need to fix anything here. Would be nice to have the docs when the mappings get merged...

**Comment by Swiftb0y** [comment]
Please merge / rebase on main to fix the CI.

**Comment by HorstBaerbel** [comment]
We've improved the mapping in this PR #12296 for Mixxx 2.4. I'm closing this PR now.

**Pull request closed without merging**
