### PR TITLE
Remove obsolete _redirects file

### PR DESCRIPTION
**Pull request by Holzhaus**
This file is written by the build_html.sh script.

### CODE REVIEW

**Comment by daschuer** [comment]
Another broken link :-/
Do we need to add this file to .gitignore that it does not re-appear from a users worktree?

**Comment by Holzhaus** [comment]
It won't, it's only written by the build script into the output directory which is already ignored.

**Comment by Holzhaus** [comment]
Merge?

**Review by daschuer — APPROVED** [review]
Yes, thank you.

**Pull request merged**
