### PR TITLE
Update copyright 2024

### PR DESCRIPTION
**Pull request by ronso0**

### CODE REVIEW

**Review by daschuer — CHANGES_REQUESTED** [review]
Did you create the changes via translation script? 
If it is a manual process, let's try to remove this hart to mauntain boilerplate. 
The tranlations are maintained at Tranifex. 
I think an update is long overdue. I can have a look tonight.

**Comment by daschuer** [comment]
https://github.com/mixxxdj/manual?tab=readme-ov-file#internationalization-i18n

**Comment by ronso0** [comment]
Hmm, somehow I assumed the po files are the source files.
Not sure how to update this then, (C) is not set in the resepective rst files, must be somewhere on Transifex.

**Review by daschuer — APPROVED** [review]
LGTM, thank you.

**Pull request merged**
