### PR TITLE
Fix pre commit

### PR DESCRIPTION
**Pull request by JoergAtGithub**
Pre-Commit didn't work for me locally on Windows:

1.) When I execute pre-commit on my command line, a dialog pops up, asking for my GitLab credentials - I have no account at GitLab
2.) Python interpreter is not found (same fix as in https://github.com/mixxxdj/mixxx/pull/11004 )

### CODE REVIEW

**Comment by daschuer** [comment]
Thank you. There are now CI errors. 
Optimize SVG files fails. Is this related to this PR?

**Comment by JoergAtGithub** [comment]
I did not see this locally - and I did not touch the SVG file. I can't explain this.

**Review by daschuer — APPROVED** [review]
LGTM, thank you.

**Comment by Swiftb0y** [comment]
@JoergAtGithub can you open another PR against the 2.3 branch?

**Comment by JoergAtGithub** [comment]
> @JoergAtGithub can you open another PR against the 2.3 branch?

I did (PR #529), but with target 2.3 CI fails - as this PR before I retargeted to main.

**Pull request merged**
